### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by hobbyquaker** [ha4us/ha4us-scripts#1]
Hi! 
I like it when my work is useful for others, I also appreciate it to be used in other contexts and environments, that's why I use MIT licensing for almost all of my projects. 
But to be honest: what I don't like is when even these very permissive MIT license terms aren't respected (`The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.`)... 
So I'm kindly asking you to just put a "Credits" section in your Readmes and point out from which projects you copied significant parts of the source code and/or concepts... 
Furthermore you should keep the original LICENSE file in the project and just add another line with your name, you could also add the years to make clear when someone contributed to the code, like e.g.:

```
The MIT License (MIT)

Copyright (c) 2017 Ulf Steinberg
Copyright (c) 2015 Sebastian Raff <hq@ccu.io> (https://github.com/hobbyquaker)
...
```
Another option would be to fork projects so the original commit history including all contributors is preserved (this is not part of the licensing terms but I think it's a fair behavior, especially when major parts of the code are used 1:1).

(This does - in my point of view - not only apply to ha4us-scripts but also to other ha4us modules...)

Regards,
Sebastian

**Comment by ulfalfa** [comment]
Hi,

thanks for your comment.

You're right I was missing this in at least ha4us-script and ha4us-hm, since here I'm following your not only your architectural path, but also copying code from your modules. So I added the information your were requesting. This ha4us stuff was mainly for my personal education and usage (that's why you don't see readmes and stuff like this) and I'm using github mainly for managing my source code.

Forking is something I still not really learned, but I'll take a look at it.

I'd like to emphasize your first sentence (I like when my work is useful for others...) . I was big fan of ccu.io and in the beginning of io.broker (at least till the time you left the project and there was no message bus and no database anymore). Then I started to have my own "io.broker" but I learned that this approach gets too complex, so that I'm currently starting over again with a more microservice like approach (so again following your architecture mqtt base style)

Cheers,
Ulf

**Comment by hobbyquaker** [comment]
Thx! And thx for your feedback too :) I think the ha4us approach is quite interesting, as far as I saw you're going a good middle way between the ioBroker concepts and the "meta-data-less" mqtt-smarthome approach. Will try to have a deeper look when I find time :)
